# Generated by Django 5.0.6 on 2024-07-04 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
                ('fono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('rol_usuario', models.CharField(choices=[('Arrendatario', 'Arrendatario'), ('Arrendador', 'Arrendador')], default='Arrendador', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Inmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('direccion', models.CharField(max_length=200)),
                ('comuna', models.CharField(max_length=50)),
                ('mts_cuadrados', models.IntegerField()),
                ('mts_totales', models.IntegerField()),
                ('precio_mensual', models.IntegerField()),
                ('cant_estacionamientos', models.IntegerField()),
                ('cant_habitaciones', models.IntegerField()),
                ('cant_banos', models.IntegerField()),
                ('disponible', models.BooleanField(default=True)),
                ('arrendador', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble_en_arriendo', to='main.usuario')),
                ('arrendatorio', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='inmueble_arrendado', to='main.usuario')),
            ],
        ),
    ]
