# Generated by Django 5.0.6 on 2024-07-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_inmueble_arrendador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inmueble',
            name='arrendador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmuebles_en_arriendo', to='main.usuario'),
        ),
    ]
